### ISSUE TITLE
cannot `pip install pymaclab=0.95.9`

### ISSUE THREAD

**Issue by fyears** [escheffel/pymaclab#32]
I am using windows 8.1 x64 with visual studio 2008 professonal installed.

I am using python 2.7.5 and pip 1.4.1 . `scipy` and `numpy` have been installed.

After I ran `pip install pymaclab` or `pip install pymaclab=0.95.9` (they should be equivalent), I got errors.

Here is `pip.log`:

```
------------------------------------------------------------
C:\Users\iamtheuser\venv\Scripts\pip-script.py run on 11/23/13 23:46:39
Downloading/unpacking pymaclab

  Getting page http://e.pypi.python.org/simple/pymaclab/
  URLs to search for versions for pymaclab:
  * http://e.pypi.python.org/simple/pymaclab/
  Analyzing links from page http://e.pypi.python.org/simple/pymaclab/
    Found link http://e.pypi.python.org/packages/source/p/pymaclab/pymaclab-0.90.1.tar.gz#md5=213d7d7c1ef3154cee3cd36fc743928e (from http://e.pypi.python.org/simple/pymaclab/), version: 0.90.1
    Found link http://e.pypi.python.org/packages/source/p/pymaclab/pymaclab-0.95.1.tar.gz#md5=89a548a511dc0b87dc36a9775fd4d3ec (from http://e.pypi.python.org/simple/pymaclab/), version: 0.95.1
    Found link http://e.pypi.python.org/packages/source/p/pymaclab/pymaclab-0.85.tar.gz#md5=b61bd0b381c18e729272fe2c89e15091 (from http://e.pypi.python.org/simple/pymaclab/), version: 0.85
    Found link http://e.pypi.python.org/packages/source/p/pymaclab/pymaclab-0.88.1.tar.gz#md5=531d60d1eee6b28013c8a4ce5b911006 (from http://e.pypi.python.org/simple/pymaclab/), version: 0.88.1
    Found link http://e.pypi.python.org/packages/source/p/pymaclab/pymaclab-0.89.1.tar.gz#md5=33fa59c2a03db774906befd5c1cd85fe (from http://e.pypi.python.org/simple/pymaclab/), version: 0.89.1
    Found link http://e.pypi.python.org/packages/source/p/pymaclab/pymaclab-0.95.9.tar.gz#md5=f8db75d123b0cb8bb29919ee33d40148 (from http://e.pypi.python.org/simple/pymaclab/), version: 0.95.9
    Found link http://e.pypi.python.org/packages/source/p/pymaclab/pymaclab-0.95.8.tar.gz#md5=5078e5a4e42dcc17772064190897a3f8 (from http://e.pypi.python.org/simple/pymaclab/), version: 0.95.8
  Using version 0.95.9 (newest of versions: 0.95.9, 0.95.8, 0.95.1, 0.90.1, 0.89.1, 0.88.1, 0.85)
  Downloading from URL http://e.pypi.python.org/packages/source/p/pymaclab/pymaclab-0.95.9.tar.gz#md5=f8db75d123b0cb8bb29919ee33d40148 (from http://e.pypi.python.org/simple/pymaclab/)
  Running setup.py egg_info for package pymaclab

    Traceback (most recent call last):

      File "<string>", line 16, in <module>

    IOError: [Errno 2] No such file or directory: 'C:\\Users\\iamtheuser\\venv\\build\\pymaclab\\setup.py'

    Complete output from command python setup.py egg_info:

    Traceback (most recent call last):

  File "<string>", line 16, in <module>

IOError: [Errno 2] No such file or directory: 'C:\\Users\\iamtheuser\\venv\\build\\pymaclab\\setup.py'

----------------------------------------

Cleaning up...

  Removing temporary dir C:\Users\iamtheuser\venv\build...
Command python setup.py egg_info failed with error code 1 in C:\Users\iamtheuser\venv\build\pymaclab

Exception information:
Traceback (most recent call last):
  File "C:\Users\iamtheuser\venv\lib\site-packages\pip\basecommand.py", line 134, in main
    status = self.run(options, args)
  File "C:\Users\iamtheuser\venv\lib\site-packages\pip\commands\install.py", line 236, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "C:\Users\iamtheuser\venv\lib\site-packages\pip\req.py", line 1134, in prepare_files
    req_to_install.run_egg_info()
  File "C:\Users\iamtheuser\venv\lib\site-packages\pip\req.py", line 259, in run_egg_info
    command_desc='python setup.py egg_info')
  File "C:\Users\iamtheuser\venv\lib\site-packages\pip\util.py", line 670, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in C:\Users\iamtheuser\venv\build\pymaclab
```

PS:  `pip install pymaclab=0.95.8` returns similar errors.

**Comment by letsgoexploring** [comment]
I have the same problem on Mac OSX 10.11.2.

**Comment by zlqs1985** [comment]
I have the sampe problem on a Win10 system
